### ISSUE TITLE
Minecraft crashes while loading mods if Patcher is not installed

### ISSUE THREAD

**Issue by dapper-gh** [Scherso/NotSoEssential#17]
Hey, thanks for the mod--I hate Sk1er's (somewhat) new monetization strategy of shoving Essential down our throats.

However, when Patcher is not installed with the latest version of NotSoEssential (1.0.3), the game crashes during the mod loading process (Forge icon is showing and the Minecraft window has spawned.) The problem disappears once Patcher is added.

For reference, I'm running Artix Linux and Forge 1.8.9, version 11.15.1.2318.

Here's the log:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (NotSoEssential-Forge-1.0.3.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 6/8/23 4:03 PM
Description: Initializing game

java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    gg/essential/cosmetics/EssentialModelRenderer.cosmeticsShouldRender(Lnet/minecraft/entity/player/EntityPlayer;)Z @71: dload_1
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: b200 3cb6 0040 9900 182a c100 4299 0011
    0x0000010: 2ac0 0044 b900 4701 0099 0005 03ac b200
    0x0000020: 3cb6 004a 9900 0503 acb2 004c 9900 0503
    0x0000030: acb8 0052 b400 58c6 001a 2ab8 0052 b400
    0x0000040: 58b6 005e 8d03 ac27 1400 5f97 9b00 0503
    0x0000050: ac2a b600 639a 000e 2ab6 0066 9a00 0704
    0x0000060: a700 0403 ac                           
  Stackmap Table:
    same_frame(@30)
    same_frame(@41)
    same_frame(@49)
    same_frame(@81)
    chop_frame(@99,1)
    same_locals_1_stack_item_frame(@100,Integer)

	at net.minecraft.client.renderer.entity.RenderPlayer.handler$zdd000$initEssentialCosmeticsLayer(RenderPlayer.java:591)
	at net.minecraft.client.renderer.entity.RenderPlayer.<init>(RenderPlayer.java:43)
	at net.minecraft.client.renderer.entity.RenderPlayer.<init>(RenderPlayer.java:30)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:207)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:481)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:168)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:114)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderPlayer.handler$zdd000$initEssentialCosmeticsLayer(RenderPlayer.java:591)
	at net.minecraft.client.renderer.entity.RenderPlayer.<init>(RenderPlayer.java:43)
	at net.minecraft.client.renderer.entity.RenderPlayer.<init>(RenderPlayer.java:30)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:207)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:481)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:168)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:114)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 6.3.2-artix1-1
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 304822208 bytes (290 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID             | Version      | Source                             |
	| ----- | -------------- | ------------ | ---------------------------------- |
	| UCH   | mcp            | 9.19         | minecraft.jar                      |
	| UCH   | FML            | 8.0.99.99    | forge-1.8.9-11.15.1.2318-1.8.9.jar |
	| UCH   | Forge          | 11.15.1.2318 | forge-1.8.9-11.15.1.2318-1.8.9.jar |
	| UCH   | essential      | 1.0.0        | Essential (forge_1.8.9).jar        |
	| UCH   | autogg         | 4.1.3        | AutoGG-4.1.3 (1.8.9).jar           |
	| UCH   | autotip        | 3.1          | Autotip-3.1 (1.8.9_forge).jar      |
	| UCH   | notsoessential | 1.0.3        | NotSoEssential-Forge-1.0.3.jar     |
	| UCH   | quickplay      | 2.0.8        | Quickplay-1.8.9-2.0.8.jar          |
	| UCH   | enhancements   | 7.7          | Vanilla+Enhancements-7.7.jar       |

	Loaded coremods (and transformers): 
FMLPlugin (NotSoEssential-Forge-1.0.3.jar)
  com.github.u9g.notsoessential.asm.ClassTransformer
	GL info: ' Vendor: 'AMD' Version: '4.6 (Compatibility Profile) Mesa 23.1.1' Renderer: 'AMD Radeon VII (vega20, LLVM 15.0.7, DRM 3.52, 6.3.2-artix1-1)'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: AMD Radeon VII (vega20, LLVM 15.0.7, DRM 3.52, 6.3.2-artix1-1) GL version 4.6 (Compatibility Profile) Mesa 23.1.1, AMD
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: §8§k_§r §aRodrigo's §4War §cStrawberry §8§k_§r
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 5800X 8-Core Processor
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6 (Compatibility Profile) Mesa 23.1.1
	OpenGlRenderer: AMD Radeon VII (vega20, LLVM 15.0.7, DRM 3.52, 6.3.2-artix1-1)
	OpenGlVendor: AMD
	CpuCount: 16
```

**Comment by Scherso** [comment]
Oh, looks like an issue with cancelling the CosmeticRenderer, that's interesting.

**Comment by Scherso** [comment]
Can you send your mods list so I can try to recreate this and patch this

**Comment by dapper-gh** [comment]
Hi! Thanks for looking into it. I don't have the original mod list from when I submitted this issue, but here's a minimal example that still triggers a crash for me:
```
~/.minecraft/mods $ sha256sum *
7ad843d6d95f4654febbf410ec389d48078f874437bb51b5cc94e68221379b32  AutoGG-4.1.3 (1.8.9).jar
e2acae749c7fc68de2ccfd681744e3fb846f14957c99e3a02690bf3c5de6c3cd  NotSoEssential-Forge-1.0.3.jar
```

**Comment by Scherso** [comment]
It's interesting, because I've tried to fix this bug, by any chance would you be willing to download a version of a mod from a automated build? I think some code changes I've done may help,
A link directly to the action's built jar is linked [here](https://github.com/Scherso/NotSoEssential/suites/13941472661/artifacts/776502750).
If that doesn't work (if I did permissions wrong), I linked a media fire download [here](https://www.mediafire.com/file/i3nmsfa9qx0tmuv/NSE-jars.zip/file).
The download you're looking for would be in the directory `NotSoEssential-Forge/build/libs/` and is named `NotSoEssential-Forge-1.0.3.jar`

**Comment by dapper-gh** [comment]
Hi, I downloaded the JAR from GitHub Actions. The crash continues to occur. I've attached the crash log, but I don't believe it has changed. It's weird that you can't recreate it.
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (NotSoEssential-Forge-1.0.3.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 6/30/23 3:05 PM
Description: Initializing game

java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    gg/essential/cosmetics/EssentialModelRenderer.cosmeticsShouldRender(Lnet/minecraft/entity/player/EntityPlayer;)Z @71: dload_1
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: b200 3cb6 0040 9900 182a c100 4299 0011
    0x0000010: 2ac0 0044 b900 4701 0099 0005 03ac b200
    0x0000020: 3cb6 004a 9900 0503 acb2 004c 9900 0503
    0x0000030: acb8 0052 b400 58c6 001a 2ab8 0052 b400
    0x0000040: 58b6 005e 8d03 ac27 1400 5f97 9b00 0503
    0x0000050: ac2a b600 639a 000e 2ab6 0066 9a00 0704
    0x0000060: a700 0403 ac                           
  Stackmap Table:
    same_frame(@30)
    same_frame(@41)
    same_frame(@49)
    same_frame(@81)
    chop_frame(@99,1)
    same_locals_1_stack_item_frame(@100,Integer)

	at net.minecraft.client.renderer.entity.RenderPlayer.handler$zcp000$initEssentialCosmeticsLayer(RenderPlayer.java:591)
	at net.minecraft.client.renderer.entity.RenderPlayer.<init>(RenderPlayer.java:43)
	at net.minecraft.client.renderer.entity.RenderPlayer.<init>(RenderPlayer.java:30)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:192)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:481)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:168)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:114)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderPlayer.handler$zcp000$initEssentialCosmeticsLayer(RenderPlayer.java:591)
	at net.minecraft.client.renderer.entity.RenderPlayer.<init>(RenderPlayer.java:43)
	at net.minecraft.client.renderer.entity.RenderPlayer.<init>(RenderPlayer.java:30)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:192)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:481)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:168)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:114)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:110)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 6.3.9-artix1-1
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1267958168 bytes (1209 MB) / 1744830464 bytes (1664 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 7 total; -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID             | Version      | Source                             |
	| ----- | -------------- | ------------ | ---------------------------------- |
	| UCH   | mcp            | 9.19         | minecraft.jar                      |
	| UCH   | FML            | 8.0.99.99    | forge-1.8.9-11.15.1.2318-1.8.9.jar |
	| UCH   | Forge          | 11.15.1.2318 | forge-1.8.9-11.15.1.2318-1.8.9.jar |
	| UCH   | essential      | 1.0.0        | Essential (forge_1.8.9).jar        |
	| UCH   | autogg         | 4.1.3        | AutoGG-4.1.3 (1.8.9).jar           |
	| UCH   | notsoessential | 1.0.3        | NotSoEssential-Forge-1.0.3.jar     |

	Loaded coremods (and transformers): 
FMLPlugin (NotSoEssential-Forge-1.0.3.jar)
  com.github.u9g.notsoessential.asm.ClassTransformer
	GL info: ' Vendor: 'AMD' Version: '4.6 (Compatibility Profile) Mesa 23.1.3' Renderer: 'AMD Radeon VII (vega20, LLVM 15.0.7, DRM 3.52, 6.3.9-artix1-1)'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: AMD Radeon VII (vega20, LLVM 15.0.7, DRM 3.52, 6.3.9-artix1-1) GL version 4.6 (Compatibility Profile) Mesa 23.1.3, AMD
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: §8§k_§r §aRodrigo's §4War §cStrawberry §8§k_§r
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 5800X 8-Core Processor
```

**Comment by MisterSheeple** [comment]
I appear to be experiencing the same crash.

**Comment by MisterSheeple** [comment]
Thank you!

**Comment by Scherso** [comment]
I'm working on fixing this, it's just a really weird bug.

**Comment by Scherso** [comment]
Anyone willing to contact me on discord, my user is: salmon5
I'm working on a fix right now.
