### ISSUE TITLE
Crash at Launch

### ISSUE THREAD

**Issue by Absterge** [Scherso/NotSoEssential#21]
I believe it's because of SimpleToggleSprint v2.3.0
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (NotSoEssential-Forge-1.0.3.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 13/03/24 12:03
Description: Initializing game

java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    gg/essential/cosmetics/EssentialModelRenderer.cosmeticsShouldRender(Lnet/minecraft/client/entity/AbstractClientPlayer;)Z @94: dload_1
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: b200 3cb6 0040 9a00 0503 ac2a c000 42b9
    0x0000010: 0046 0100 b900 4b01 0099 0005 04ac b200
    0x0000020: 3cb6 004e 9900 112a c000 42b9 0051 0100
    0x0000030: 9900 0503 acb2 003c b600 5499 0005 03ac
    0x0000040: b200 5699 0005 03ac b800 5cb4 0062 c600
    0x0000050: 1a2a b800 5cb4 0062 b600 688d 03ac 2714
    0x0000060: 0069 979b 0005 03ac 2ab6 006d 9a00 0e2a
    0x0000070: b600 709a 0007 04a7 0004 03ac          
  Stackmap Table:
    same_frame(@11)
    same_frame(@30)
    same_frame(@53)
    same_frame(@64)
    same_frame(@72)
    same_frame(@104)
    same_frame(@122)
    same_locals_1_stack_item_frame(@123,Integer)

	at net.minecraft.client.renderer.entity.RenderPlayer.handler$zdj000$initEssentialCosmeticsLayer(RenderPlayer.java:590)
	at net.minecraft.client.renderer.entity.RenderPlayer.<init>(RenderPlayer.java:43)
	at net.minecraft.client.renderer.entity.RenderPlayer.<init>(RenderPlayer.java:30)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:207)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:481)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:173)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:117)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderPlayer.handler$zdj000$initEssentialCosmeticsLayer(RenderPlayer.java:590)
	at net.minecraft.client.renderer.entity.RenderPlayer.<init>(RenderPlayer.java:43)
	at net.minecraft.client.renderer.entity.RenderPlayer.<init>(RenderPlayer.java:30)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:207)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:481)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:173)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:117)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_381, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM GraalVM EE 21.3.7 (mixed mode), Oracle Corporation
	Memory: 1576473352 bytes (1503 MB) / 2025324544 bytes (1931 MB) up to 2386558976 bytes (2276 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx2560m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M6_pre1 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version      | Source                                       |
	| ----- | ------------------ | ------------ | -------------------------------------------- |
	| UCH   | mcp                | 9.19         | minecraft.jar                                |
	| UCH   | FML                | 8.0.99.99    | forge-1.8.9-11.15.1.2318-1.8.9-universal.jar |
	| UCH   | Forge              | 11.15.1.2318 | forge-1.8.9-11.15.1.2318-1.8.9-universal.jar |
	| UCH   | essential          | 1.0.0        | Essential (forge_1.8.9).jar                  |
	| UCH   | notsoessential     | 1.0.3        | NotSoEssential-Forge-1.0.3.jar               |
	| UCH   | simpletogglesprint | 2.3.0        | SimpleToggleSprint-2.3.0.jar                 |
	| UCH   | wikitools          | 2.6.6        | wikitools-2.6.6.jar                          |`

**Comment by Scherso** [comment]
oh my god

**Comment by Yeecy-sketch** [comment]
Can confirm, happening to me as well if I start with the AutoGG or the HyCord mod.
Logs: https://mclo.gs/k4hRc7t

**Comment by HowardZHY** [comment]
still with latest ESSENTIAL
